"""Add Topic model

Revision ID: 477113689e95
Revises: aa89723515d9
Create Date: 2025-04-01 14:46:38.313755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '477113689e95'
down_revision = 'aa89723515d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topic')
    # ### end Alembic commands ###
