"""Changed daily_recitation to Text

Revision ID: 9adcf45fd407
Revises: 54dfac79e1ea
Create Date: 2025-03-09 19:50:23.348662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9adcf45fd407'
down_revision = '54dfac79e1ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scriptures', schema=None) as batch_op:
        batch_op.alter_column('daily_recitation',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scriptures', schema=None) as batch_op:
        batch_op.alter_column('daily_recitation',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
